#!/bin/sh

#
# Script used by hostapps updater to flash bootloader onto internal media
#

set -o errexit

# machine specific data
uboot_file="u-boot-edison.bin"
uboot_block_size=512
uboot_seek_blocks=2048

uboot_env_file="u-boot-envs/edison-blankcdc.bin"
uboot_env_block_size=512
uboot_env_seek_blocks=6144

device="/dev/mmcblk0"

update_files="uboot uboot_env"

for i in $update_files; do
	current_update_file=$(eval echo \$${i}_file)
	block_size=$(eval echo \$${i}_block_size)
	seek_blocks=$(eval echo \$${i}_seek_blocks)

	# calculate size and md5sum of the binary to update from the update bundle
	update_size=$(ls -al /resin-boot/$current_update_file | awk '{print $5}')
	update_md5sum=$(md5sum /resin-boot/$current_update_file | awk '{print $1'})

	# calculate number of bytes to skip when computing the checksum of the data we want to update (i.e. the data already written to $device)
	let skip_bytes=$block_size*$seek_blocks

	# calculate md5sum of the data already written to $device, using $update_size bytes and skipping $skip_bytes from $device
	existing_md5sum=$(dd if=$device of=/tmp/update_temp skip=$skip_bytes bs=1 count=$update_size &>/dev/null && md5sum /tmp/update_temp | awk '{print $1}')
	rm -rf /tmp/update_temp

	if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
		echo "Flashing $current_update_file to $device"
		dd if=/resin-boot/$current_update_file of=$device conv=fdatasync seek=$seek_blocks bs=$block_size
	fi
done
